// This file is auto-generated by @hey-api/openapi-ts

export type AttachmentPublic = {
    id: string;
    filename: string;
    mime_type: string;
    extraction_status: string;
    created_at: string;
};

export type AttachmentSignedUrl = {
    url: string;
    expires_in: number;
};

export type Body_ingestMail = {
    /**
     * JSON con los metadatos del correo, validado como MailStageCreate: external_id, sender, received_at, subject y body.
     */
    mail: string;
    /**
     * JSON con un identificador externo estable por adjunto, en el mismo orden que los archivos enviados en el campo 'files'.
     */
    attachment_external_ids?: string;
    files?: Array<(string)>;
};

export type Body_login_login_access_token = {
    grant_type?: (string | null);
    username: string;
    password: string;
    scope?: string;
    client_id?: (string | null);
    client_secret?: (string | null);
};

export type HTTPValidationError = {
    detail?: Array<ValidationError>;
};

export type MailPublic = {
    subject?: (string | null);
    sender: string;
    received_at: string;
    id: string;
    user_id: string;
    source_id: string;
    created_at: string;
    has_attachments?: boolean;
};

export type MailResponse = {
    subject?: (string | null);
    sender: string;
    received_at: string;
    id: string;
    user_id: string;
    source_id: string;
    created_at: string;
    has_attachments?: boolean;
    body?: (string | null);
    attachments?: Array<AttachmentPublic>;
};

export type MailStagePublic = {
    ingestion_id?: (string | null);
    external_id: string;
    status: string;
    mail_id?: (string | null);
    result_summary?: {
        [key: string]: unknown;
    };
};

export type Message = {
    message: string;
};

export type NewPassword = {
    token: string;
    new_password: string;
};

export type PrivateUserCreate = {
    email: string;
    password: string;
    full_name: string;
    is_verified?: boolean;
};

export type QuestionPublic = {
    question: string;
    answer: string;
    citations?: Array<{
        [key: string]: unknown;
    }>;
    id: string;
    user_id: string;
    created_at: string;
};

export type Token = {
    access_token: string;
    token_type?: string;
};

export type UpdatePassword = {
    current_password: string;
    new_password: string;
};

export type UserCreate = {
    email: string;
    is_active?: boolean;
    is_superuser?: boolean;
    full_name?: (string | null);
    password: string;
};

export type UserPublic = {
    email: string;
    is_active?: boolean;
    is_superuser?: boolean;
    full_name?: (string | null);
    id: string;
    created_at?: (string | null);
};

export type UserRegister = {
    email: string;
    password: string;
    full_name?: (string | null);
};

export type UsersPublic = {
    data: Array<UserPublic>;
    count: number;
};

export type UserUpdate = {
    email?: (string | null);
    is_active?: boolean;
    is_superuser?: boolean;
    full_name?: (string | null);
    password?: (string | null);
};

export type UserUpdateMe = {
    full_name?: (string | null);
    email: string;
};

export type ValidationError = {
    loc: Array<(string | number)>;
    msg: string;
    type: string;
    input?: unknown;
    ctx?: {
        [key: string]: unknown;
    };
};

export type LoginLoginAccessTokenData = {
    formData: Body_login_login_access_token;
};

export type LoginLoginAccessTokenResponse = (Token);

export type LoginTestTokenResponse = (UserPublic);

export type LoginRecoverPasswordData = {
    email: string;
};

export type LoginRecoverPasswordResponse = (Message);

export type LoginResetPasswordData = {
    requestBody: NewPassword;
};

export type LoginResetPasswordResponse = (Message);

export type LoginRecoverPasswordHtmlContentData = {
    email: string;
};

export type LoginRecoverPasswordHtmlContentResponse = (string);

export type MailsReadMailsData = {
    limit?: number;
    skip?: number;
};

export type MailsReadMailsResponse = (Array<MailPublic>);

export type IngestMailData = {
    formData: Body_ingestMail;
};

export type IngestMailResponse = (MailStagePublic);

export type MailsReadMailData = {
    id: string;
};

export type MailsReadMailResponse = (MailResponse);

export type MailsDeleteMailData = {
    id: string;
};

export type MailsDeleteMailResponse = (Message);

export type GetMailAttachmentSignedUrlData = {
    attachmentId: string;
    download?: boolean;
    mailId: string;
};

export type GetMailAttachmentSignedUrlResponse = (AttachmentSignedUrl);

export type ReadMailAttachmentTextData = {
    attachmentId: string;
    mailId: string;
};

export type ReadMailAttachmentTextResponse = (string);

export type PrivateCreateUserData = {
    requestBody: PrivateUserCreate;
};

export type PrivateCreateUserResponse = (UserPublic);

export type QuestionsReadQuestionsData = {
    limit?: number;
    skip?: number;
};

export type QuestionsReadQuestionsResponse = (Array<QuestionPublic>);

export type QuestionsCreateQuestionData = {
    questionIn: string;
};

export type QuestionsCreateQuestionResponse = (QuestionPublic);

export type QuestionsReadQuestionData = {
    id: string;
};

export type QuestionsReadQuestionResponse = (QuestionPublic);

export type QuestionsDeleteQuestionData = {
    id: string;
};

export type QuestionsDeleteQuestionResponse = (Message);

export type UsersReadUsersData = {
    limit?: number;
    skip?: number;
};

export type UsersReadUsersResponse = (UsersPublic);

export type UsersCreateUserData = {
    requestBody: UserCreate;
};

export type UsersCreateUserResponse = (UserPublic);

export type UsersReadUserMeResponse = (UserPublic);

export type UsersDeleteUserMeResponse = (Message);

export type UsersUpdateUserMeData = {
    requestBody: UserUpdateMe;
};

export type UsersUpdateUserMeResponse = (UserPublic);

export type UsersUpdatePasswordMeData = {
    requestBody: UpdatePassword;
};

export type UsersUpdatePasswordMeResponse = (Message);

export type UsersRegisterUserData = {
    requestBody: UserRegister;
};

export type UsersRegisterUserResponse = (UserPublic);

export type UsersReadUserByIdData = {
    userId: string;
};

export type UsersReadUserByIdResponse = (UserPublic);

export type UsersUpdateUserData = {
    requestBody: UserUpdate;
    userId: string;
};

export type UsersUpdateUserResponse = (UserPublic);

export type UsersDeleteUserData = {
    userId: string;
};

export type UsersDeleteUserResponse = (Message);

export type UtilsTestEmailData = {
    emailTo: string;
};

export type UtilsTestEmailResponse = (Message);

export type UtilsHealthCheckResponse = (boolean);