"""init schema

Revision ID: 267251fa76ec
Revises: 4a7ffde01dd0
Create Date: 2026-06-09 20:17:57.908411

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '267251fa76ec'
down_revision = '4a7ffde01dd0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'user',
        sa.Column(
            'email_provider',
            sqlmodel.sql.sqltypes.AutoString(length=255),
            nullable=False,
            server_default='unknown',
        ),
    )
    op.alter_column('user', 'email_provider', server_default=None)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'email_provider')
    # ### end Alembic commands ###
