"""Initial schema

Revision ID: 5b5066d7a2a4
Revises: 75acdb188513
Create Date: 2026-06-25 18:50:29.160512

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '5b5066d7a2a4'
down_revision = '75acdb188513'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
