"""Initial schema

Revision ID: 5cd57fd065ca
Revises: 5b5066d7a2a4
Create Date: 2026-06-26 00:09:23.248753

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '5cd57fd065ca'
down_revision = '5b5066d7a2a4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('question', sa.Column('answer', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('question', 'answer')
    # ### end Alembic commands ###
