"""Initial schema

Revision ID: 75acdb188513
Revises: fe1374b06ae3
Create Date: 2026-06-20 21:41:30.944035

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '75acdb188513'
down_revision = 'fe1374b06ae3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('question',
    sa.Column('question', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.alter_column('chunk', 'chunk_text',
               existing_type=sa.VARCHAR(length=1500),
               type_=sqlmodel.sql.sqltypes.AutoString(length=900),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('chunk', 'chunk_text',
               existing_type=sqlmodel.sql.sqltypes.AutoString(length=900),
               type_=sa.VARCHAR(length=1500),
               existing_nullable=False)
    op.drop_table('question')
    # ### end Alembic commands ###
