"""Initial schema

Revision ID: c0c73c2b9319
Revises: 5cd57fd065ca
Create Date: 2026-06-28 22:15:14.227471

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'c0c73c2b9319'
down_revision = '5cd57fd065ca'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('chunk', 'chunk_text',
               existing_type=sa.VARCHAR(length=900),
               type_=sqlmodel.sql.sqltypes.AutoString(length=800),
               existing_nullable=False)
    op.add_column('question', sa.Column('sources', sa.JSON(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('question', 'sources')
    op.alter_column('chunk', 'chunk_text',
               existing_type=sqlmodel.sql.sqltypes.AutoString(length=800),
               type_=sa.VARCHAR(length=900),
               existing_nullable=False)
    # ### end Alembic commands ###
