"""init schema

Revision ID: c8029608b169
Revises: e818a8474533
Create Date: 2026-06-11 17:58:56.337040

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'c8029608b169'
down_revision = 'e818a8474533'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mail', sa.Column('subject', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True))
    op.add_column('mail', sa.Column('body', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('mail', sa.Column('sender', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False))
    op.add_column('mail', sa.Column('date', sa.DateTime(timezone=True), nullable=False))
    op.drop_column('mail', 'source_email')
    op.drop_column('mail', 'title')
    op.drop_column('mail', 'received_at')
    op.drop_column('mail', 'content')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mail', sa.Column('content', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('mail', sa.Column('received_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False))
    op.add_column('mail', sa.Column('title', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('mail', sa.Column('source_email', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.drop_column('mail', 'date')
    op.drop_column('mail', 'sender')
    op.drop_column('mail', 'body')
    op.drop_column('mail', 'subject')
    # ### end Alembic commands ###
