"""Initial schema

Revision ID: e29c79d60a71
Revises: 3867b1ec632b
Create Date: 2026-06-15 00:20:34.978860

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'e29c79d60a71'
down_revision = '3867b1ec632b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('chunk', 'chunk_text',
               existing_type=sa.VARCHAR(length=1000),
               type_=sqlmodel.sql.sqltypes.AutoString(length=1500),
               existing_nullable=False)
    op.drop_column('mail', 'body')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mail', sa.Column('body', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.alter_column('chunk', 'chunk_text',
               existing_type=sqlmodel.sql.sqltypes.AutoString(length=1500),
               type_=sa.VARCHAR(length=1000),
               existing_nullable=False)
    # ### end Alembic commands ###
