"""init schema

Revision ID: e818a8474533
Revises: 267251fa76ec
Create Date: 2026-06-10 23:11:35.181151

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'e818a8474533'
down_revision = '267251fa76ec'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'email_provider')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('email_provider', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
