"""Initial schema

Revision ID: fe1374b06ae3
Revises: e29c79d60a71
Create Date: 2026-06-18 18:21:05.584713

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from pgvector.sqlalchemy import Vector


# revision identifiers, used by Alembic.
revision = 'fe1374b06ae3'
down_revision = 'e29c79d60a71'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chunk', sa.Column('embedding', Vector(1536), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('chunk', 'embedding')
    # ### end Alembic commands ###
